# Generated by Django 4.2.2 on 2023-06-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('building', models.CharField(max_length=10000)),
                ('date_of_birth', models.DateField()),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('token', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('move_in_date', models.DateField()),
                ('move_out_date', models.DateField()),
            ],
        ),
    ]
